import { controlBodyBracesRule } from "../../src/rules/control-body-braces-rule";
import { createRuleTester } from "../helpers/rule-tester";

createRuleTester().run("control-body-braces", controlBodyBracesRule, {
    valid: [
        {
            code: [
                "class Sample {",
                "    run(values: string[], flag: boolean): string[] {",
                "        if (flag) {",
                "            return values;",
                "        } else if (values.length > 1) {",
                "            return values.slice();",
                "        } else {",
                "            return [];",
                "        }",
                "",
                "        for (const value of values) {",
                "            console.log(value);",
                "        }",
                "",
                "        while (flag) {",
                "            return values;",
                "        }",
                "",
                "        do {",
                "            return values;",
                "        } while (flag);",
                "",
                "        return values;",
                "    }",
                "}",
            ].join("\n"),
        },
    ],
    invalid: [
        {
            code: [
                "class Sample {",
                "    run(values: string[], flag: boolean): string[] {",
                "        if (flag)",
                "            return values;",
                "        else if (values.length > 1)",
                "            return values.slice();",
                "        else",
                "            return [];",
                "",
                "        for (const value of values)",
                "            console.log(value);",
                "",
                "        while (flag)",
                "            return values;",
                "",
                "        do",
                "            console.log(values.length);",
                "        while (flag);",
                "",
                "        return values;",
                "    }",
                "}",
            ].join("\n"),
            output: [
                "class Sample {",
                "    run(values: string[], flag: boolean): string[] {",
                "        if (flag) {",
                "            return values;",
                "        } else if (values.length > 1) {",
                "            return values.slice();",
                "        } else {",
                "            return [];",
                "        }",
                "",
                "        for (const value of values) {",
                "            console.log(value);",
                "        }",
                "",
                "        while (flag) {",
                "            return values;",
                "        }",
                "",
                "        do {",
                "            console.log(values.length);",
                "        } while (flag);",
                "",
                "        return values;",
                "    }",
                "}",
            ].join("\n"),
            errors: [
                { messageId: "controlBodyBraces" },
                { messageId: "controlBodyBraces" },
                { messageId: "controlBodyBraces" },
                { messageId: "controlBodyBraces" },
                { messageId: "controlBodyBraces" },
                { messageId: "controlBodyBraces" },
            ],
        },
    ],
});
