import { ifLeadingSpacingRule } from "../../src/rules/if-leading-spacing-rule";
import { createRuleTester } from "../helpers/rule-tester";

createRuleTester().run("if-leading-spacing", ifLeadingSpacingRule, {
    valid: [
        {
            code: [
                "class Sample {",
                "    test(flag: boolean): string {",
                "        const value = flag ? 'yes' : 'no';",
                "",
                "        if (!flag) {",
                "            return value;",
                "        }",
                "",
                "        return value;",
                "    }",
                "}",
            ].join("\n"),
        },
        {
            code: [
                "class Sample {",
                "    test(flag: boolean): string {",
                "        if (!flag) {",
                "            return 'no';",
                "        }",
                "",
                "        return 'yes';",
                "    }",
                "}",
            ].join("\n"),
        },
    ],
    invalid: [
        {
            code: [
                "class Sample {",
                "    test(flag: boolean): string {",
                "        const value = flag ? 'yes' : 'no';",
                "        if (!flag) {",
                "            return value;",
                "        }",
                "",
                "        return value;",
                "    }",
                "}",
            ].join("\n"),
            output: [
                "class Sample {",
                "    test(flag: boolean): string {",
                "        const value = flag ? 'yes' : 'no';",
                "",
                "        if (!flag) {",
                "            return value;",
                "        }",
                "",
                "        return value;",
                "    }",
                "}",
            ].join("\n"),
            errors: [{ messageId: "ifLeadingSpacing" }],
        },
        {
            code: [
                "class Sample {",
                "    test(values: string[]): string[] {",
                "        for (const value of values) {",
                "            if (value === 'stop') {",
                "                return values;",
                "            }",
                "        } if (values.length === 0) {",
                "            return values;",
                "        }",
                "",
                "        return values;",
                "    }",
                "}",
            ].join("\n"),
            output: [
                "class Sample {",
                "    test(values: string[]): string[] {",
                "        for (const value of values) {",
                "            if (value === 'stop') {",
                "                return values;",
                "            }",
                "        }",
                "",
                "        if (values.length === 0) {",
                "            return values;",
                "        }",
                "",
                "        return values;",
                "    }",
                "}",
            ].join("\n"),
            errors: [{ messageId: "ifLeadingSpacing" }],
        },
    ],
});
